### ISSUE TITLE
Running riser from 4.2v lipo ? BMS features ? Deep sleep

### ISSUE THREAD

**Issue by shodanx2** [platima/ESP32-CX-Riser#2]
Can the board currently run off a lipo battery (4.25v to 3.2v) or lifepo4 (3.6 to 2.5v) ?

What is deep sleep quiescent current within the acceptable input voltage range ?

Is there a jumper to connect VCC to ADC (read battery voltage and allow first important BMS feature, preventing over-discharge by staying in sleep if voltage goes below minimum)

Second most important feature would be charging the cell while powered off DC/USB power (if ADC is connected, you can skip the proper BMS and slow charge through a resistor and transistor and implement over charging by turning off the transistor whenever ADC is not reading a "acceptable to charge" voltage)

It should be possible to start the ESP32 on battery, plug usb in, disconnect battery, reconnect battery and disconnect usb without the ESP32 powering off or glitching

**Comment by platima** [comment]
That is all very possible but outside the scope of this project.

1. As per the source uploaded, you can provide a stable 3.3V input, else if using the LDO in the V1.1 design (not sure I pushed that up yet) then you can run it with roughly 4-12V DC input depending on the exact LDO

2. For deep sleep please see the relevant Espressif module datasheet

3. Yes you can read battery voltage using an ADC pin, you'd just want to put it through a transistor attached to a digital pin or similar so you only sink current from the battery for the read, and then cut it off again.

4. Charging any external batteries is also outside of the scope of this project. In the future I may consider battery circuitry, but it's not in the current pipeline. I will add it to a list of feature requests.

5. I don't see any reason with the current schematic that you could not switch between 3.3V regulated and 4-12V (aka 5V input) unregulated.
